
services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        INSTALL_PYTHON_VERSION: 3.11.0
        INSTALL_NODE_VERSION: 22.0.0
    image: "anime-development"
    ports:
      - "5000:5000"
      - "2992:2992"
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
      - ./dev.db:/tmp/dev.db

  flask-prod:
    build:
      context: .
      target: production
      args:
        INSTALL_PYTHON_VERSION: 3.11.0
        INSTALL_NODE_VERSION: 22.0.0
    image: "anime-production"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
      - ./dev.db:/tmp/dev.db

  manage:
    build:
      context: .
      target: development
      args:
        INSTALL_PYTHON_VERSION: 3.11.0
        INSTALL_NODE_VERSION: 22.0.0
    entrypoint: flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "anime-manage"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
      - ./dev.db:/tmp/dev.db

volumes:
  node-modules:
